app_root:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    @AppBundle/static/index.html.twig

app_admin:
    path: /admin/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    @AppBundle/static/admin.html.twig

app_user:
    path: /user/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    @AppBundle/static/user.html.twig